name: user_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_database: ^11.1.0
  flutter_geofire: ^2.0.3
  flutter_polyline_points: ^2.1.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.9.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  loading_animation_widget: ^1.2.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  restart_app: ^1.2.1
  url_launcher: ^6.3.0
  intl_phone_number_input: ^0.7.4
  pin_code_fields: ^8.0.1
  pinput: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
